dataset:
  target: dataset.LRHRRef.LRHRRefDataset
  params:
    # Path to the file list.
    dataroot_hr: /content/CRefDiff_Testing/data_img/hr_tiles
    dataroot_lr: /content/CRefDiff_Testing/data_img/LR
    dataroot_ref: /content/CRefDiff_Testing/data_img/hr_tiles
    split: "val"
    data_len: 182
    use_ColorJitter: false
    gt_as_ref: false

data_loader:
  batch_size: 8
  shuffle: false
  num_workers: 8
  drop_last: false

batch_transform:
  target: dataset.batch_transform.IdentityBatchTransform
